# railway.toml - Frontend service configuration
[build]
builder = "DOCKERFILE"
dockerfilePath = "client/Dockerfile"
watchPaths = ["./**"]

[deploy]
healthcheckPath = "/health"  # Health check endpoint
healthcheckTimeout = 60  # Longer timeout for more reliable checks
startCommand = ""  # Let Dockerfile CMD handle this
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
RAILWAY_DOCKERFILE_PATH = "client/Dockerfile"
